FROM ubuntu:16.04

RUN apt-get update && apt-get install -y autoconf
RUN apt-get update && apt-get install -y libtool
RUN apt-get update && apt-get install -y g++
RUN apt-get update && apt-get install -y pkg-config
RUN apt-get update && apt-get install -y libboost-system-dev
RUN apt-get update && apt-get install -y libboost-filesystem-dev
RUN apt-get update && apt-get install -y libboost-chrono-dev
RUN apt-get update && apt-get install -y libboost-program-options-dev
RUN apt-get update && apt-get install -y libboost-test-dev
RUN apt-get update && apt-get install -y libboost-thread-dev
RUN apt-get update && apt-get install -y libssl-dev
RUN apt-get update && apt-get install -y libevent-dev
RUN apt-get update && apt-get install -y wget
RUN apt-get clean

RUN \
    mkdir -p ~/temp/berkley-db && \
    cd       ~/temp/berkley-db && \
    wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz' && \
    tar  -xzvf  db-4.8.30.NC.tar.gz && \
    rm      -rf db-4.8.30.NC.tar.gz && \
    cd          db-4.8.30.NC/build_unix/ && \
    ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=/usr/local && \
    make install && \
    cd / && rm -rf ~/temp
