.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. equibit_qt test_equibit_qt
clean: FORCE
	$(MAKE) -C .. equibit_qt_clean test_equibit_qt_clean
check: FORCE
	$(MAKE) -C .. test_equibit_qt_check
equibit-qt equibit-qt.exe: FORCE
	 $(MAKE) -C .. equibit_qt
